/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ATM_system;

import javax.swing.JOptionPane;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.*;

/**
 *
 * @author karishma
 */
public class ATMS extends javax.swing.JFrame {

    /**
     * Creates new form ATMS
     */
    public ATMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonEmptyButton2 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonEmptyButton1 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonEmptyButton3 = new javax.swing.JButton();
        jButtonEnter = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanelMainMenuScreen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelBalance = new javax.swing.JLabel();
        jLabelCash = new javax.swing.JLabel();
        jLabelBalanceReciept = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelChangePin = new javax.swing.JLabel();
        jLabelFastCash = new javax.swing.JLabel();
        jLabelMenuItem6 = new javax.swing.JLabel();
        jPanelFastCashScreen = new javax.swing.JPanel();
        jLabelWarningFastCash = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabelRs100 = new javax.swing.JLabel();
        jLabelRs500 = new javax.swing.JLabel();
        jLabelRs1000 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabelRs2000 = new javax.swing.JLabel();
        jLabelRs5000 = new javax.swing.JLabel();
        jLabelRs10000 = new javax.swing.JLabel();
        jPanelNewPinScreen = new javax.swing.JPanel();
        jLabelNewPin = new javax.swing.JLabel();
        jLabelNewPinValue = new javax.swing.JLabel();
        jPanelLoginScreen = new javax.swing.JPanel();
        jLabelPin = new javax.swing.JLabel();
        jLabelPinValue = new javax.swing.JLabel();
        jPanelWithdrawCash = new javax.swing.JPanel();
        jLabeWithdrawCashText = new javax.swing.JLabel();
        jLabelWithdrawCashValue = new javax.swing.JLabel();
        jPanelShowBalanceScreen = new javax.swing.JPanel();
        jLabeShowlBalanceText = new javax.swing.JLabel();
        jLabelShowBalanceValue = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jBtnLeftPanel1 = new javax.swing.JButton();
        jBtnLeftPanel2 = new javax.swing.JButton();
        jBtnLeftPanel3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jBtnRightPanel1 = new javax.swing.JButton();
        jBtnRightPanel2 = new javax.swing.JButton();
        jBtnRightPanel3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSide = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(125, 189, 237));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(java.awt.Color.red);
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(java.awt.Color.orange);
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonEnter.setBackground(java.awt.Color.green);
        jButtonEnter.setLabel("Enter");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEmptyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonEmptyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEmptyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEmptyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEmptyButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEmptyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 180));
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        jPanelMainMenuScreen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMainMenuScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelMainMenuScreen.setMinimumSize(new java.awt.Dimension(180, 42));
        jPanelMainMenuScreen.setPreferredSize(new java.awt.Dimension(50, 53));
        jPanelMainMenuScreen.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelBalance.setText("Balance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jPanel1.add(jLabelBalance, gridBagConstraints);

        jLabelCash.setText("Cash");
        jLabelCash.setMaximumSize(null);
        jLabelCash.setMinimumSize(null);
        jLabelCash.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jPanel1.add(jLabelCash, gridBagConstraints);

        jLabelBalanceReciept.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBalanceReciept.setText("Balance Reciept");
        jLabelBalanceReciept.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabelBalanceReciept, gridBagConstraints);

        jPanelMainMenuScreen.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelChangePin.setText("Change Pin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 80, 0, 0);
        jPanel2.add(jLabelChangePin, gridBagConstraints);

        jLabelFastCash.setText("Fast Cash");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 80, 0, 0);
        jPanel2.add(jLabelFastCash, gridBagConstraints);

        jLabelMenuItem6.setMaximumSize(new java.awt.Dimension(45, 13));
        jLabelMenuItem6.setMinimumSize(new java.awt.Dimension(45, 13));
        jLabelMenuItem6.setPreferredSize(new java.awt.Dimension(45, 13));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 80, 0, 0);
        jPanel2.add(jLabelMenuItem6, gridBagConstraints);

        jPanelMainMenuScreen.add(jPanel2);

        jPanel4.add(jPanelMainMenuScreen);

        jPanelFastCashScreen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFastCashScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelFastCashScreen.setMinimumSize(new java.awt.Dimension(180, 42));
        jPanelFastCashScreen.setPreferredSize(new java.awt.Dimension(50, 53));
        jPanelFastCashScreen.setLayout(new javax.swing.OverlayLayout(jPanelFastCashScreen));

        jLabelWarningFastCash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWarningFastCash.setAlignmentX(0.5F);
        jLabelWarningFastCash.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelFastCashScreen.add(jLabelWarningFastCash);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabelRs100.setText("100");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jPanel7.add(jLabelRs100, gridBagConstraints);

        jLabelRs500.setText("500");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jPanel7.add(jLabelRs500, gridBagConstraints);

        jLabelRs1000.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRs1000.setText("1000");
        jLabelRs1000.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jPanel7.add(jLabelRs1000, gridBagConstraints);

        jPanel9.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabelRs2000.setText("2000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jPanel8.add(jLabelRs2000, gridBagConstraints);

        jLabelRs5000.setText("5000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jPanel8.add(jLabelRs5000, gridBagConstraints);

        jLabelRs10000.setText("10000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 0);
        jPanel8.add(jLabelRs10000, gridBagConstraints);

        jPanel9.add(jPanel8);

        jPanelFastCashScreen.add(jPanel9);

        jPanel4.add(jPanelFastCashScreen);

        jPanelNewPinScreen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNewPinScreen.setLayout(new java.awt.GridBagLayout());

        jLabelNewPin.setText("Enter new PIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanelNewPinScreen.add(jLabelNewPin, gridBagConstraints);

        jLabelNewPinValue.setToolTipText("");
        jLabelNewPinValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabelNewPinValue.setMaximumSize(null);
        jLabelNewPinValue.setMinimumSize(null);
        jLabelNewPinValue.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanelNewPinScreen.add(jLabelNewPinValue, gridBagConstraints);

        jPanel4.add(jPanelNewPinScreen);

        jPanelLoginScreen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLoginScreen.setLayout(new java.awt.GridBagLayout());

        jLabelPin.setText("Enter PIN");
        jLabelPin.setMaximumSize(new java.awt.Dimension(180, 18));
        jLabelPin.setMinimumSize(new java.awt.Dimension(180, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanelLoginScreen.add(jLabelPin, gridBagConstraints);

        jLabelPinValue.setToolTipText("");
        jLabelPinValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabelPinValue.setMaximumSize(null);
        jLabelPinValue.setMinimumSize(null);
        jLabelPinValue.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanelLoginScreen.add(jLabelPinValue, gridBagConstraints);

        jPanel4.add(jPanelLoginScreen);

        jPanelWithdrawCash.setPreferredSize(new java.awt.Dimension(200, 174));
        jPanelWithdrawCash.setLayout(new java.awt.GridBagLayout());

        jLabeWithdrawCashText.setText("Enter amount to withdraw");
        jLabeWithdrawCashText.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanelWithdrawCash.add(jLabeWithdrawCashText, new java.awt.GridBagConstraints());

        jLabelWithdrawCashValue.setMaximumSize(null);
        jLabelWithdrawCashValue.setMinimumSize(null);
        jLabelWithdrawCashValue.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanelWithdrawCash.add(jLabelWithdrawCashValue, gridBagConstraints);

        jPanel4.add(jPanelWithdrawCash);

        jPanelShowBalanceScreen.setPreferredSize(new java.awt.Dimension(200, 174));
        jPanelShowBalanceScreen.setLayout(new java.awt.GridBagLayout());

        jLabeShowlBalanceText.setText("Your balance is");
        jLabeShowlBalanceText.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanelShowBalanceScreen.add(jLabeShowlBalanceText, new java.awt.GridBagConstraints());

        jLabelShowBalanceValue.setMaximumSize(null);
        jLabelShowBalanceValue.setMinimumSize(null);
        jLabelShowBalanceValue.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanelShowBalanceScreen.add(jLabelShowBalanceValue, gridBagConstraints);

        jPanel4.add(jPanelShowBalanceScreen);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jBtnLeftPanel1.setLabel("->");
        jBtnLeftPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLeftPanel1MouseClicked(evt);
            }
        });
        jBtnLeftPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLeftPanel1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jBtnLeftPanel1, gridBagConstraints);

        jBtnLeftPanel2.setLabel("->");
        jBtnLeftPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLeftPanel2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jBtnLeftPanel2, gridBagConstraints);

        jBtnLeftPanel3.setLabel("->");
        jBtnLeftPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLeftPanel3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jBtnLeftPanel3, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jBtnRightPanel1.setLabel("<-");
        jBtnRightPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRightPanel1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jBtnRightPanel1, gridBagConstraints);

        jBtnRightPanel2.setLabel("<-");
        jBtnRightPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRightPanel2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jBtnRightPanel2, gridBagConstraints);

        jBtnRightPanel3.setLabel("<-");
        jBtnRightPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRightPanel3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jBtnRightPanel3, gridBagConstraints);

        jTextAreaSide.setEditable(false);
        jTextAreaSide.setColumns(20);
        jTextAreaSide.setFont(new java.awt.Font("TlwgTypewriter", 0, 14)); // NOI18N
        jTextAreaSide.setRows(5);
        jTextAreaSide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane1.setViewportView(jTextAreaSide);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Enum for states of the app
    enum STATE {
        BALANCE, CASH, BALANCE_RECEIPT, CHANGE_PIN, FAST_CASH, MINI_STATEMENT,
        LOGGED_IN_MAIN_MENU, LOGGED_OUT;
    }

    // Object of the above enum and is set to logged out when the app starts
    private STATE applicationState = STATE.LOGGED_OUT;

    // Setting a default balance for the default user
    private int balance = 200000;

    // Default pin
    private int PIN = 1234;

    private void setState(STATE state) {
        applicationState = state;
        setScreen();
    }

    private void disableAllSideButtons() {
        jBtnLeftPanel1.setEnabled(false);
        jBtnLeftPanel2.setEnabled(false);
        jBtnLeftPanel3.setEnabled(false);
        jBtnRightPanel1.setEnabled(false);
        jBtnRightPanel3.setEnabled(false);
        jBtnRightPanel2.setEnabled(false);
    }

    private void enableAllSideButtons() {
        jBtnLeftPanel1.setEnabled(true);
        jBtnLeftPanel2.setEnabled(true);
        jBtnLeftPanel3.setEnabled(true);
        jBtnRightPanel1.setEnabled(true);
        jBtnRightPanel3.setEnabled(true);
        jBtnRightPanel2.setEnabled(true);
    }

    private void showLoginScreen() {
        jPanelLoginScreen.setVisible(true);
        jPanelMainMenuScreen.setVisible(false);
        jPanelNewPinScreen.setVisible(false);
        jPanelShowBalanceScreen.setVisible(false);
        jPanelWithdrawCash.setVisible(false);
        jPanelFastCashScreen.setVisible(false);
    }

    private void showMainMenu() {
        jPanelMainMenuScreen.setVisible(true);
        jPanelLoginScreen.setVisible(false);
        jPanelNewPinScreen.setVisible(false);
        jPanelShowBalanceScreen.setVisible(false);
        jPanelWithdrawCash.setVisible(false);
        jPanelFastCashScreen.setVisible(false);
    }

    private void showBalance() {
        jPanelShowBalanceScreen.setVisible(true);
        jPanelMainMenuScreen.setVisible(false);
        jPanelLoginScreen.setVisible(false);
        jPanelNewPinScreen.setVisible(false);
        jPanelWithdrawCash.setVisible(false);
        jPanelFastCashScreen.setVisible(false);
    }

    private void showWithdrawCash() {
        jPanelWithdrawCash.setVisible(true);
        jPanelShowBalanceScreen.setVisible(false);
        jPanelMainMenuScreen.setVisible(false);
        jPanelLoginScreen.setVisible(false);
        jPanelNewPinScreen.setVisible(false);
        jPanelFastCashScreen.setVisible(false);
    }

    private void showNewPin() {
        jPanelNewPinScreen.setVisible(true);
        jPanelWithdrawCash.setVisible(false);
        jPanelShowBalanceScreen.setVisible(false);
        jPanelMainMenuScreen.setVisible(false);
        jPanelLoginScreen.setVisible(false);
        jPanelFastCashScreen.setVisible(false);
    }

    private void showFastCash() {
        jPanelFastCashScreen.setVisible(true);
        jPanelNewPinScreen.setVisible(false);
        jPanelWithdrawCash.setVisible(false);
        jPanelShowBalanceScreen.setVisible(false);
        jPanelMainMenuScreen.setVisible(false);
        jPanelLoginScreen.setVisible(false);
    }

    private void showBalanceReceipt() {
        jPanelFastCashScreen.setVisible(false);
        jPanelNewPinScreen.setVisible(false);
        jPanelWithdrawCash.setVisible(false);
        jPanelShowBalanceScreen.setVisible(false);
        jPanelMainMenuScreen.setVisible(false);
        jPanelLoginScreen.setVisible(false);

        ZoneId zonedId = ZoneId.of("Asia/Kolkata");
        ZonedDateTime zdt = ZonedDateTime.now( zonedId );

        String billText = "                  Balace BILL                 \n" +
                "=========================\n" +
                "Date:\t" + zdt + "\n" +
                "Balance:\tRs " + balance + "";

        jTextAreaSide.setText(billText);
    }

    private void setScreen() {
        switch (applicationState) {
            case LOGGED_OUT:
                showLoginScreen();
                disableAllSideButtons();
                break;
            case LOGGED_IN_MAIN_MENU:
                showMainMenu();
                enableAllSideButtons();
                jBtnRightPanel3.setEnabled(false);
                break;
            case BALANCE:
                showBalance();
                disableAllSideButtons();
                break;
            case CASH:
                showWithdrawCash();
                disableAllSideButtons();
                break;
            case BALANCE_RECEIPT:
                showBalanceReceipt();
                disableAllSideButtons();
                break;
            case CHANGE_PIN:
                showNewPin();
                disableAllSideButtons();
                break;
            case FAST_CASH:
                showFastCash();
                enableAllSideButtons();
                break;
        }
    }

    // Function called when 0 is clicked
    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "0");

    }//GEN-LAST:event_jButton0ActionPerformed

    // Function called when 1 is clicked
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "1");


    }//GEN-LAST:event_jButton1ActionPerformed

    // Function called when 2 is clicked
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "2");

    }//GEN-LAST:event_jButton2ActionPerformed

    // Function called when 3 is clicked
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "3");

    }//GEN-LAST:event_jButton3ActionPerformed

    // Function called when 4 is clicked
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "4");

    }//GEN-LAST:event_jButton4ActionPerformed

    // Function called when 5 is clicked
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "5");

    }//GEN-LAST:event_jButton5ActionPerformed

    // Function called when 6 is clicked
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "6");

    }//GEN-LAST:event_jButton6ActionPerformed

    // Function called when 7 is clicked
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "7");

    }//GEN-LAST:event_jButton7ActionPerformed

    // Function called when 8 is clicked
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "8");

    }//GEN-LAST:event_jButton8ActionPerformed

    // Function called when 9 is clicked
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText(label.getText() + "9");

    }//GEN-LAST:event_jButton9ActionPerformed

    // Function called when "Cancel" is clicked
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        if (applicationState == STATE.BALANCE) {
            jLabelShowBalanceValue.setText("");
            setState(STATE.LOGGED_IN_MAIN_MENU);
        } else if (applicationState == STATE.LOGGED_IN_MAIN_MENU) {
            System.exit(0);
        } else if (applicationState == STATE.CASH) {
            jLabelWithdrawCashValue.setText("");
            setState(STATE.LOGGED_IN_MAIN_MENU);
        } else if (applicationState == STATE.FAST_CASH) {
            jLabelWarningFastCash.setText("");
            setState(STATE.LOGGED_IN_MAIN_MENU);
        } else if (applicationState == STATE.BALANCE_RECEIPT) {
            jTextAreaSide.setText("");
            setState(STATE.LOGGED_IN_MAIN_MENU);
        }
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Function called when "Clear" is clicked
    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        javax.swing.JLabel label = null;
        switch (applicationState) {
            case LOGGED_OUT:
                label = jLabelPinValue;
                break;
            case CASH:
                label = jLabelWithdrawCashValue;
                break;
            case CHANGE_PIN:
                label = jLabelNewPinValue;
                break;
        }
        if (label != null)
            label.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    // Function called when button corresponding to "Balance Receipt" is clicked in the main menu
    private void jBtnLeftPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLeftPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLeftPanel1MouseClicked

    // Function called when "Enter" is clicked
    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        // If user has not yet logged in
        if (applicationState == STATE.LOGGED_OUT) {
            if (PIN == Integer.parseInt(jLabelPinValue.getText())) {
                // Changing state to main menu
                setState(STATE.LOGGED_IN_MAIN_MENU);
            } else {
                // Showing error message instead of "Enter the PIN" text
                jLabelPin.setText("Please enter a valid pin");
            }
        }
        // If user is withdrawing cash
        else if (applicationState == STATE.CASH) {
            int withdrawnMoney;
            try {
                // Parsing the amount entered as an Integer
                withdrawnMoney  = Integer.parseInt(jLabelWithdrawCashValue.getText());
                // If money to withdraw is more than balance we show "Invalid" in the TextField where the user has
                // entered the balance
                if (withdrawnMoney > balance || withdrawnMoney == 0) {
                    jLabelWithdrawCashValue.setText("Invalid");
                    return;
                }
                // If money is less than balance then accept the withdrawal and reduce balance
                else {
                    balance -= withdrawnMoney;
                    // Going back to the main menu after accepting the withdrawal
                    setState(STATE.LOGGED_IN_MAIN_MENU);
                }
            }
            // If it fails for some reason we'll aske the user to re-enter
            catch (Exception e) {
                jLabelWithdrawCashValue.setText("Invalid");
            }
        }
        else if (applicationState == STATE.CHANGE_PIN) {
            try {
                int newPin = Integer.parseInt(jLabelNewPinValue.getText());
                if (newPin/10000 <= 0) {
                    PIN = newPin;
                    setState(STATE.LOGGED_IN_MAIN_MENU);
                } else {
                    jLabelNewPin.setText("Invalid pin. Please enter a 4 digit pin");
                }
            } catch (Exception e){
                jLabelNewPin.setText("Invalid pin. Please enter a 4 digit pin");
            }
        }

    }//GEN-LAST:event_jButtonEnterActionPerformed


    // Called when window is created
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setState(applicationState);
    }//GEN-LAST:event_formWindowActivated

    private void jBtnLeftPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLeftPanel1ActionPerformed
        // String balance = 10000;
        if (applicationState == STATE.LOGGED_IN_MAIN_MENU) {
            setState(STATE.BALANCE);
            jLabelShowBalanceValue.setText(String.valueOf(balance));
        }  else if (applicationState == STATE.FAST_CASH) {
            try {
                int withdrawnMoney = Integer.parseInt(jLabelRs100.getText());
                if (withdrawnMoney > balance) {
                    jLabelWarningFastCash.setText("Amount greater than balance");
                } else {
                    balance -= withdrawnMoney;
                    setState(STATE.LOGGED_IN_MAIN_MENU);
                }
            } catch (Exception e) {
                jLabelWarningFastCash.setText("Invalid");
            }

        }
    }//GEN-LAST:event_jBtnLeftPanel1ActionPerformed

    private void jBtnLeftPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLeftPanel2ActionPerformed
        // TODO add your handling code here:
        if (applicationState == STATE.LOGGED_IN_MAIN_MENU) {
            setState(STATE.CASH);
        } else if (applicationState == STATE.FAST_CASH) {
            try {
                int withdrawnMoney = Integer.parseInt(jLabelRs500.getText());
                if (withdrawnMoney > balance) {
                    jLabelWarningFastCash.setText("Amount greater than balance");
                } else {
                    balance -= withdrawnMoney;
                    setState(STATE.LOGGED_IN_MAIN_MENU);
                }
            } catch (Exception e) {
                jLabelWarningFastCash.setText("Invalid");
            }

        }
    }//GEN-LAST:event_jBtnLeftPanel2ActionPerformed

    private void jBtnLeftPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLeftPanel3ActionPerformed
        // TODO add your handling code here:
        if (applicationState == STATE.LOGGED_IN_MAIN_MENU) {
            setState(STATE.BALANCE_RECEIPT);
        } else if (applicationState == STATE.FAST_CASH) {
            try {
                int withdrawnMoney = Integer.parseInt(jLabelRs1000.getText());
                if (withdrawnMoney > balance) {
                    jLabelWarningFastCash.setText("Amount greater than balance");
                } else {
                    balance -= withdrawnMoney;
                    setState(STATE.LOGGED_IN_MAIN_MENU);
                }
            } catch (Exception e) {
                jLabelWarningFastCash.setText("Invalid");
            }

        }
    }//GEN-LAST:event_jBtnLeftPanel3ActionPerformed

    private void jBtnRightPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRightPanel1ActionPerformed
        // TODO add your handling code here:
        if (applicationState == STATE.LOGGED_IN_MAIN_MENU) {
            setState(STATE.CHANGE_PIN);
        } else if (applicationState == STATE.FAST_CASH) {
            try {
                int withdrawnMoney = Integer.parseInt(jLabelRs2000.getText());
                if (withdrawnMoney > balance) {
                    jLabelWarningFastCash.setText("Amount greater than balance");
                } else {
                    balance -= withdrawnMoney;
                    setState(STATE.LOGGED_IN_MAIN_MENU);
                }
            } catch (Exception e) {
                jLabelWarningFastCash.setText("Invalid");
            }

        }
    }//GEN-LAST:event_jBtnRightPanel1ActionPerformed

    private void jBtnRightPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRightPanel2ActionPerformed
        // TODO add your handling code here:
        if (applicationState == STATE.LOGGED_IN_MAIN_MENU) {
            setState(STATE.FAST_CASH);
        } else if (applicationState == STATE.FAST_CASH) {
            try {
                int withdrawnMoney = Integer.parseInt(jLabelRs5000.getText());
                if (withdrawnMoney > balance) {
                    jLabelWarningFastCash.setText("Amount greater than balance");
                } else {
                    balance -= withdrawnMoney;
                    setState(STATE.LOGGED_IN_MAIN_MENU);
                }
            } catch (Exception e) {
                jLabelWarningFastCash.setText("Invalid");
            }

        }
    }//GEN-LAST:event_jBtnRightPanel2ActionPerformed

    private void jBtnRightPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRightPanel3ActionPerformed
        // TODO add your handling code here:
        if (applicationState == STATE.FAST_CASH) {
            try {
                int withdrawnMoney = Integer.parseInt(jLabelRs10000.getText());
                if (withdrawnMoney > balance) {
                    jLabelWarningFastCash.setText("Amount greater than balance");
                } else {
                    balance -= withdrawnMoney;
                    setState(STATE.LOGGED_IN_MAIN_MENU);
                }
            } catch (Exception e) {
                jLabelWarningFastCash.setText("Invalid");
            }
        }
    }//GEN-LAST:event_jBtnRightPanel3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLeftPanel1;
    private javax.swing.JButton jBtnLeftPanel2;
    private javax.swing.JButton jBtnLeftPanel3;
    private javax.swing.JButton jBtnRightPanel1;
    private javax.swing.JButton jBtnRightPanel2;
    private javax.swing.JButton jBtnRightPanel3;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonEmptyButton1;
    private javax.swing.JButton jButtonEmptyButton2;
    private javax.swing.JButton jButtonEmptyButton3;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabeShowlBalanceText;
    private javax.swing.JLabel jLabeWithdrawCashText;
    private javax.swing.JLabel jLabelBalance;
    private javax.swing.JLabel jLabelBalanceReciept;
    private javax.swing.JLabel jLabelCash;
    private javax.swing.JLabel jLabelChangePin;
    private javax.swing.JLabel jLabelFastCash;
    private javax.swing.JLabel jLabelMenuItem6;
    private javax.swing.JLabel jLabelNewPin;
    private javax.swing.JLabel jLabelNewPinValue;
    private javax.swing.JLabel jLabelPin;
    private javax.swing.JLabel jLabelPinValue;
    private javax.swing.JLabel jLabelRs100;
    private javax.swing.JLabel jLabelRs1000;
    private javax.swing.JLabel jLabelRs10000;
    private javax.swing.JLabel jLabelRs2000;
    private javax.swing.JLabel jLabelRs500;
    private javax.swing.JLabel jLabelRs5000;
    private javax.swing.JLabel jLabelShowBalanceValue;
    private javax.swing.JLabel jLabelWarningFastCash;
    private javax.swing.JLabel jLabelWithdrawCashValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelFastCashScreen;
    private javax.swing.JPanel jPanelLoginScreen;
    private javax.swing.JPanel jPanelMainMenuScreen;
    private javax.swing.JPanel jPanelNewPinScreen;
    private javax.swing.JPanel jPanelShowBalanceScreen;
    private javax.swing.JPanel jPanelWithdrawCash;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSide;
    // End of variables declaration//GEN-END:variables
}
